deployment:
  tasks:
    - export DEPLOYPATH=/home/sabn3321/public_html/crud/
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp create.blade.php $DEPLOYPATH
    - /bin/cp database.php $DEPLOYPATH
    - /bin/cp edit.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp main.php $DEPLOYPATH
    - /bin/cp proses.php $DEPLOYPATH
    - /bin/cp tambah_data.php $DEPLOYPATH

     